[package]
name = "mkprj"
version = "1.0.2"
edition = "2021"

[dependencies]
anyhow = "1.0.86"
dirs = "5.0.1"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0.120"
subprocess = "0.2.9"
